/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TechnoCraft (https://sketchfab.com/TechnoCraft)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/camera-lens-3c9afba12cd94e2694c5213c271d579e
Title: Camera Lens
*/

import { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model({ onReady, ...props }) {
    const { nodes, materials } = useGLTF('/camera_lens.glb')

    const frontGlassRef = useRef(null)
    const secondGlassRef = useRef(null)
    const thirdGlassRef = useRef(null)
    const fourthGlassRef = useRef(null)
    const fifthGlassRef = useRef(null)
    const sixthGlassRef = useRef(null)

    const topRingRef = useRef(null)
    const bottomRingRef = useRef(null)
    const redRingRef = useRef(null)
    const frontBezelRef = useRef(null)
    const rearMountRef = useRef(null)
    const infoWindowRef = useRef(null)
    const switchPanelRef = useRef(null)
    const brandingPanelRef = useRef(null)

    useEffect(() => {
        if (
            !frontGlassRef.current ||
            !secondGlassRef.current ||
            !thirdGlassRef.current ||
            !fourthGlassRef.current ||
            !fifthGlassRef.current ||
            !sixthGlassRef.current ||
            !topRingRef.current ||
            !bottomRingRef.current ||
            !redRingRef.current ||
            !frontBezelRef.current ||
            !rearMountRef.current ||
            !infoWindowRef.current ||
            !switchPanelRef.current ||
            !brandingPanelRef.current
        ) {
            return
        }

        onReady?.({
            frontGlass: frontGlassRef.current,
            secondGlass: secondGlassRef.current,
            thirdGlass: thirdGlassRef.current,
            fourthGlass: fourthGlassRef.current,
            fifthGlass: fifthGlassRef.current,
            sixthGlass: sixthGlassRef.current,
            topRing: topRingRef.current,
            bottomRing: bottomRingRef.current,
            redRing: redRingRef.current,
            frontBezel: frontBezelRef.current,
            rearMount: rearMountRef.current,
            infoWindow: infoWindowRef.current,
            switchPanel: switchPanelRef.current,
            brandingPanel: brandingPanelRef.current,
        })
    }, [onReady])

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    {/* 1. TOP RING */}
                    <group ref={topRingRef}>
                        <group position={[0, 26.251, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['top_ring_Material_#476_0'].geometry}
                                material={materials.Material_476}
                                position={[-41.166, -17.537, 0]}
                            />
                        </group>
                    </group>

                    {/* 2. BOTTOM RING & its label (logo_5) */}
                    <group ref={bottomRingRef}>
                        <group position={[0, -20.914, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['bottom_ring_Material_#476_0'].geometry}
                                material={materials.Material_476}
                                position={[124.192, 29.628, 0]}
                            />
                        </group>
                        <group position={[0, -20.914, 0.058]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['logo_5_Material_#310_0'].geometry}
                                material={materials.Material_310}
                                position={[124.192, 29.628, 0]}
                            />
                        </group>
                    </group>

                    {/* 3. RED RING & its label (logo_11) */}
                    <group ref={redRingRef}>
                        <group position={[0, 28.502, 0]}>
                            <group position={[37.225, 24.651, 0]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes['Line002_Material_#343_0'].geometry}
                                    material={materials.Material_343}
                                />
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes['Line002_Material_#345_0'].geometry}
                                    material={materials.Material_345}
                                />
                            </group>
                        </group>
                        <group position={[0, 28.564, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['logo_11_Material_#346_0'].geometry}
                                material={materials.Material_346}
                                position={[37.225, 24.651, 0]}
                            />
                        </group>
                    </group>

                    {/* 4. BRANDING PANEL (Canon Logo & details) */}
                    <group ref={brandingPanelRef}>
                        <group position={[0, -0.126, 36.72]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.canon_logo__0.geometry}
                                material={materials.canon_logo__0}
                                position={[35.993, 70.406, 8.84]}
                            />
                        </group>
                        <group position={[0, -0.126, 36.583]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['Object012_Material_#286_0'].geometry}
                                material={materials.Material_286}
                                position={[35.993, 76.173, 8.84]}
                            />
                        </group>
                        <group position={[0, -0.126, 36.716]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['Object013_Material_#286_0'].geometry}
                                material={materials.Material_286}
                                position={[35.993, 74.433, 8.84]}
                            />
                        </group>
                        <group position={[0, -0.126, 36.755]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['logo_1_Material_#428_0'].geometry}
                                material={materials.Material_428}
                                position={[35.993, 70.406, 8.84]}
                            />
                        </group>
                        <group position={[0, -0.126, 36.758]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['logo_2_Material_#425_0'].geometry}
                                material={materials.Material_425}
                                position={[35.993, 70.406, 8.84]}
                            />
                        </group>
                        <group position={[0, -0.126, 36.78]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['logo_3_Material_#340_0'].geometry}
                                material={materials.Material_340}
                                position={[35.993, 70.406, 8.84]}
                            />
                        </group>
                    </group>

                    {/* 5. SWITCH PANEL & BUTTONS / SLIDERS */}
                    <group ref={switchPanelRef}>
                        {/* Panel Housing */}
                        <group position={[-35.961, 2.528, 6.803]} rotation={[0, -0.044, 0]}>
                            <group position={[78.544, 7.323, -7.194]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes['Object020_Material_#392_0'].geometry}
                                    material={materials.Material_392}
                                />
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes['Object020_Material_#394_0'].geometry}
                                    material={materials.Material_394}
                                />
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes['Object020_Material_#391_0'].geometry}
                                    material={materials.Material_391}
                                />
                            </group>
                        </group>
                        {/* Panel Logos */}
                        <group position={[-35.987, 2.528, 6.803]} rotation={[0, -0.044, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['logo_9_Material_#395_0'].geometry}
                                material={materials.Material_395}
                                position={[78.544, 7.323, -7.194]}
                            />
                        </group>
                        <group position={[-35.999, 2.528, 6.802]} rotation={[0, -0.044, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['logo_10_Material_#390_0'].geometry}
                                material={materials.Material_390}
                                position={[78.544, 7.323, -7.194]}
                            />
                        </group>
                        {/* Switch 1 */}
                        <group position={[-37.97, 2.72, 15.563]} rotation={[-Math.PI / 2, 0, 0]}>
                            <group rotation={[-Math.PI, 0, 1.134]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes['Capsule001_Material_#286_0'].geometry}
                                    material={materials.Material_286}
                                    position={[0, 0.944, -7.515]}
                                />
                            </group>
                            <group position={[-0.294, -0.136, 3]} rotation={[-Math.PI, 0, 1.134]} scale={0.954}>
                                <group position={[2.55, -4.526, -4.516]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes['Object027_Material_#348_0'].geometry}
                                        material={materials.Material_348}
                                    />
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes['Object027_Material_#388_0'].geometry}
                                        material={materials.Material_388}
                                    />
                                </group>
                            </group>
                        </group>
                        {/* Switch 1 Label */}
                        <group
                            position={[-38.264, 5.72, 15.698]}
                            rotation={[Math.PI / 2, 0, 1.134]}
                            scale={0.954}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['logo_12_Material_#326_0'].geometry}
                                material={materials.Material_326}
                                position={[2.55, -4.526, -4.516]}
                            />
                        </group>
                        {/* Switch 2 */}
                        <group
                            position={[-42.904, 2.824, 0.026]}
                            rotation={[-Math.PI / 2, 0, -0.436]}
                            scale={0.896}>
                            <group rotation={[-Math.PI, 0, 1.134]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes['Capsule002_Material_#286_0'].geometry}
                                    material={materials.Material_286}
                                    position={[0, 0.944, -7.515]}
                                />
                            </group>
                            <group position={[-0.294, -0.136, 3]} rotation={[-Math.PI, 0, 1.134]} scale={0.954}>
                                <group position={[2.55, -4.526, -4.516]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes['Object028_Material_#348_0'].geometry}
                                        material={materials.Material_348}
                                    />
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes['Object028_Material_#388_0'].geometry}
                                        material={materials.Material_388}
                                    />
                                </group>
                            </group>
                        </group>
                        {/* Switch 2 Label */}
                        <group
                            position={[-43.194, 5.512, 0.024]}
                            rotation={[Math.PI / 2, 0, Math.PI / 2]}
                            scale={0.855}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['logo_13_Material_#326_0'].geometry}
                                material={materials.Material_326}
                                position={[2.55, -4.526, -4.516]}
                            />
                        </group>
                    </group>

                    {/* 6. INFO WINDOW (Focus Distance Scale) */}
                    <group ref={infoWindowRef}>
                        <group position={[39.8, -1.026, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                            <group position={[-31.468, 0, 9.957]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes['Object014_Material_#365_0'].geometry}
                                    material={materials.Material_365}
                                />
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes['Object014_Material_#364_0'].geometry}
                                    material={materials.Material_364}
                                />
                            </group>
                        </group>
                        <group position={[39.848, -1.026, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['logo_8_Material_#479_0'].geometry}
                                material={materials.Material_479}
                                position={[-31.468, 0, 9.957]}
                            />
                        </group>
                    </group>

                    {/* 7. FRONT BEZEL RING */}
                    <group ref={frontBezelRef}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['Circle001_Material_#474_0'].geometry}
                            material={materials.Material_474}
                            position={[0, 58.37, 0]}
                            rotation={[-Math.PI / 2, 0, 0]}
                        />
                    </group>

                    {/* 8. REAR MOUNT & END CAP */}
                    <group ref={rearMountRef}>
                        <group position={[0, -49.86, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['end_cap001_Material_#341_0'].geometry}
                                material={materials.Material_341}
                                position={[35.993, 72.178, 0]}
                            />
                        </group>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['Cylinder003_Material_#63_0'].geometry}
                            material={materials.Material_63}
                            position={[0, -48.703, 0]}
                            rotation={[-Math.PI / 2, 0, 0]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['Sphere001_Material_#290_0'].geometry}
                            material={materials.Material_290}
                            position={[-30.54, -39.513, 15.004]}
                            rotation={[1.667, 0.244, -2.142]}
                        />
                    </group>

                    {/* 9. CENTRAL INNER CHASSIS / BARREL (STATIC) */}
                    <group position={[0, -3.387, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['Line007_Material_#475_0'].geometry}
                            material={materials.Material_475}
                            position={[35.993, 12.101, 0]}
                        />
                    </group>
                    <group position={[0, -3.387, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['Object029_Material_#308_0'].geometry}
                            material={materials.Material_308}
                            position={[35.993, 12.101, 0]}
                        />
                    </group>
                    <group position={[0, -3.387, -0.04]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['logo_4_Material_#351_0'].geometry}
                            material={materials.Material_351}
                            position={[35.993, 12.101, 0]}
                        />
                    </group>
                    <group position={[0, -3.387, 0.113]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['logo_6_Material_#326_0'].geometry}
                            material={materials.Material_326}
                            position={[35.993, 12.101, 0]}
                        />
                    </group>
                    <group position={[0.042, -3.387, 0.042]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['logo_7_Material_#307_0'].geometry}
                            material={materials.Material_307}
                            position={[35.993, 12.101, 0]}
                        />
                    </group>
                    <group position={[0, -0.796, 37.451]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['logo_14_Material_#478_0'].geometry}
                            material={materials.Material_478}
                            position={[35.993, 9.51, -37.516]}
                        />
                    </group>
                    {/* Small buttons/details on body right side */}
                    <group position={[40.934, 1.723, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['Object025_Material_#282_0'].geometry}
                            material={materials.Material_282}
                            position={[-34.018, 0, 7.208]}
                        />
                    </group>
                    <group position={[41.374, 1.723, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.888}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['Object026_Material_#282_0'].geometry}
                            material={materials.Material_282}
                            position={[-34.018, 0, 7.208]}
                        />
                    </group>

                    {/* 10. GLASS LENSES (ANIME) */}
                    <group position={[0, -1.954, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            ref={frontGlassRef}
                            castShadow
                            receiveShadow
                            geometry={nodes['Sphere002_Material_#473_0'].geometry}
                            material={materials.Material_473}
                            position={[0, 0, 46.552]}
                        />
                        <mesh
                            ref={secondGlassRef}
                            castShadow
                            receiveShadow
                            geometry={nodes['Sphere003_Material_#473_0'].geometry}
                            material={materials.Material_473}
                            position={[0, 0, 39.072]}
                            scale={[0.936, 1, 0.739]}
                        />
                        <mesh
                            ref={thirdGlassRef}
                            castShadow
                            receiveShadow
                            geometry={nodes['Sphere004_Material_#473_0'].geometry}
                            material={materials.Material_473}
                            position={[0, 0, 0.697]}
                            scale={[0.534, 0.57, 0.128]}
                        />
                        <mesh
                            ref={fourthGlassRef}
                            castShadow
                            receiveShadow
                            geometry={nodes['Sphere005_Material_#473_0'].geometry}
                            material={materials.Material_473}
                            position={[0, 0, -12.1]}
                            scale={[0.534, 0.57, 0.306]}
                        />
                        <mesh
                            ref={fifthGlassRef}
                            castShadow
                            receiveShadow
                            geometry={nodes['Sphere006_Material_#473_0'].geometry}
                            material={materials.Material_473}
                            position={[0, 0, -43.735]}
                            scale={[0.534, 0.57, 0.281]}
                        />
                        <mesh
                            ref={sixthGlassRef}
                            castShadow
                            receiveShadow
                            geometry={nodes['Sphere007_Material_#473_0'].geometry}
                            material={materials.Material_473}
                            position={[0, 0, -46.418]}
                            rotation={[Math.PI, 0, 0]}
                            scale={[0.534, 0.57, 0.234]}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/camera_lens.glb')
